# Site settings
title: Test Bench
header-img: img/home-bg.jpg
email: matthew@screamingjungle.com
copyright_name: ...
description: "test bench and education"
baseurl: ""
url: ""
twitter_username: 
github_username:  
facebook_username:  
email_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
